# See https://developers.cloudflare.com/workers/wrangler/configuration/

name = "std-rs-redirect-worker"
compatibility_date = "2022-11-30"
workers_dev = false
main = "build/worker/shim.mjs"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.production]
routes = [
    { pattern = "std.rs", custom_domain = true },
    { pattern = "n.std.rs", custom_domain = true }
]

[env.staging]
name = "std-rs-redirect-worker-staging"
routes = [
    { pattern = "std-rs-redirect-worker-staging.stdrs.dev", custom_domain = true },
    { pattern = "n.std-rs-redirect-worker-staging.stdrs.dev", custom_domain = true }
]
