name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
